from fpdf import FPDF

pdf = FPDF()
pdf.set_auto_page_break(auto=True, margin=15)
pdf.add_page()
pdf.set_font('Arial', 'B', 16)
pdf.cell(0, 10, 'NiyanTrak Demo Dataset Update', ln=True)
pdf.ln(5)
pdf.set_font('Arial', '', 12)
pdf.multi_cell(0, 8, 'This PDF summarizes the dataset addition and seed integration made in the NiyanTrak project. It includes the new JSON dataset file, the updated seed script, and instructions for usage.')
pdf.ln(5)
pdf.set_font('Arial', 'B', 12)
pdf.cell(0, 8, 'Added Files:', ln=True)
pdf.set_font('Arial', '', 12)
pdf.multi_cell(0, 8, '- backend/data/demoDataset.json: small demo dataset with users, alerts, incidents, and checklists.')
pdf.multi_cell(0, 8, '- backend/utils/seed.js: updated to import and seed MongoDB from demoDataset.json.')
pdf.ln(5)
pdf.set_font('Arial', 'B', 12)
pdf.cell(0, 8, 'Demo Dataset Contents', ln=True)
pdf.set_font('Arial', '', 12)
pdf.multi_cell(0, 8, 'The JSON dataset includes example entries for:')
pdf.multi_cell(0, 8, '1. Users (admin, employee, fireman)')
pdf.multi_cell(0, 8, '2. Alerts (fire, overload, ventilation)')
pdf.multi_cell(0, 8, '3. Incidents (near-miss and incident report examples)')
pdf.multi_cell(0, 8, '4. Checklists (preshift and equipment checks with AI risk metadata)')
pdf.ln(5)
pdf.set_font('Arial', 'B', 12)
pdf.cell(0, 8, 'Usage Instructions', ln=True)
pdf.set_font('Arial', '', 12)
pdf.multi_cell(0, 8, '1. Ensure MongoDB is running locally.')
pdf.multi_cell(0, 8, '2. Open a terminal in the project root.')
pdf.multi_cell(0, 8, '3. Run: cd backend && node utils/seed.js')
pdf.multi_cell(0, 8, '4. The seed script clears existing demo collections and loads the new demo dataset into MongoDB.')
pdf.ln(5)
pdf.set_font('Arial', 'B', 12)
pdf.cell(0, 8, 'Verification', ln=True)
pdf.set_font('Arial', '', 12)
pdf.multi_cell(0, 8, 'The updated seed script was checked for syntax with node --check backend/utils/seed.js and passed successfully.')
pdf.output('..\\demo_dataset_update.pdf')
